name: clear_bricks
description: Old style brick game.

version: 1.1.0+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  overlay_support: ^1.2.1
  soundpool: ^2.3.0
  google_mobile_ads: ^1.2.0
  connectivity: ^3.0.6
  shared_preferences: ^2.0.13
  dynamic_color: ^0.1.0
  dynamic_colorscheme: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/material.png
    - assets/audios/